version: "3"

services:
  home:
    container_name: home
    build:
      context: ../servers
      dockerfile: Dockerfile.default
    ports:
      - "8082:8080"
    environment:
      - GIN_MODE=debug
      - KAFKA_BROKERS=13.124.40.62:9092
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: home
    depends_on:
      - fluent-bit
    networks:
      - app-network

  # payment:
  #   container_name: payment
  #   build:
  #     context: ../servers
  #     dockerfile: Dockerfile.payment
  #   ports:
  #     - "8081:8080"
  #   logging:
  #     driver: fluentd
  #     options:
  #       fluentd-address: localhost:24224
  #       tag: payment

  fluent-bit:
    container_name: fluent-bit
    hostname: fluent-bit
    image: fluent/fluent-bit:latest
    ports:
      - "24224:24224"
      - "2020:2020"
    volumes:
      - ../configs/fluentbit/fluentbit.conf:/fluent-bit/etc/fluent-bit.conf
      - ../configs/fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ../logs:/var/log/flb-storage/
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
        reservations:
          cpus: "0.05"
          memory: 64M
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
